import React from "react";
import { Inter } from "next/font/google";

import StyledComponentsRegistry from "../lib/AntdRegistry";

import "./globals.css";
import ReactQueryProvider from "@/lib/ReactQueryProvider";
import WelcomeDialog from "./components/WelcomeDialog";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body className={inter.className}>
      <ReactQueryProvider>
        <StyledComponentsRegistry>
          <WelcomeDialog />
          {children}
        </StyledComponentsRegistry>
      </ReactQueryProvider>
    </body>
  </html>
);

export default RootLayout;
